apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    run: tomcat
  name: tomcat2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tomcat
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: tomcat
    spec:
      containers:
      - image: registry.example.com:5000/tomcat
        imagePullPolicy: Always
        name: tomcat2
        resources: {}
        securityContext: 
          privileged: true
