---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's http port.
  labels:
    application: test
  name: test
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    deploymentConfig: test

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    application: test
  name: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: test
        deploymentConfig: test
      name: test
    spec:
      containers:
      - image: abcsys.cn:5000/tomcat
        imagePullPolicy: Always
        name: test
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
