apiVersion: v1
kind: Endpoints
metadata:
  name: gluster-endpoints
subsets:
- addresses:
  - ip: 10.10.49.242
  ports:
  - port: 1
    protocol: TCP
- addresses:
  - ip: 10.10.49.224
  ports:
  - port: 1
    protocol: TCP
- addresses:
  - ip: 10.10.49.243
  ports:
  - port: 1
    protocol: TCP
