apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-pv-4
  labels:
    pv-number: pv4
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteMany
  glusterfs:
    endpoints: gluster-endpoints
    path: /volume4
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
