apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-claim-4
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
      storage: 2Gi
  selector:
    matchLabels:
      pv-number: pv4
