apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-pv-1
  labels:
    pv-number: pv1

spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  glusterfs:
    endpoints: gluster-endpoints
    path: /volume1
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
