apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-pv-3
  labels:
    pv-number: pv3
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  glusterfs:
    endpoints: gluster-endpoints
    path: /volume3
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
