apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-claim-2
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
      storage: 5Gi
  selector:
    matchLabels:
      pv-number: pv2
