apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-pv-nosecret
  labels:
    pv-number: pv-nosecret
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteMany
  glusterfs:
    endpoints: gluster-endpoints
    path: /volume-registry
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
