apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-pv-2
  labels:
    pv-number: pv2
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  glusterfs:
    endpoints: gluster-endpoints
    path: /volume2
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
